### PR TITLE
InputFile: allow arbitrary FUNCT<n> sections

### LINKED ISSUE #385: [BUG] 4C can't handle more than 30 functions any more
## Bug Description: What's going wrong?

It seems like with #373 the ability of 4C to handle more than 30 functions was removed.

## Expectations
4C should be able to handle arbitrarily many functions (maybe limited by some integer value range, but not by an arbitrarily chosen value of 30).

## Steps to Reproduce
The attached input file with 500 functions works as expected with 6a75fd555dad8a603d76ee921e38f2e012fd55f9 but fails with the current `main` branch with an error like
```
  Section 'FUNCT31' is not a valid section name.
```

Attached input file (has to be renamed to `.dat`)
[a_lot_of_functions.txt](https://github.com/user-attachments/files/18823298/a_lot_of_functions.txt)

## Related Issues and Merge Requests

- Blocks
- Follows
- Related to #373
- Part of
- Composed of

## Interested Parties

@knarfnitram @sebproell

### PR DESCRIPTION
**Pull request by sebproell**
Closes #385

### CODE REVIEW

File: src/global_data/4C_global_data_read.cpp [hunk 1]
```diff
@@ -83,7 +83,8 @@ namespace
       auto valid_functions = functionmanager.valid_function_lines();
 
       // TODO Move the function number inside the general function section to stop relying
-      // on explicit function numbers.
+      // on explicit function numbers. The magic number 30 is equal to the highest number appearing
+      // in the test files.
       for (unsigned i : std::views::iota(1, 30))
```
Comment (isteinbrecher) [inline src/global_data/4C_global_data_read.cpp:88]: Is there a reason we still need this? Should the fix in `is_section_known` not allow for all function IDs?

Comment (sebproell) [inline src/global_data/4C_global_data_read.cpp:88]: I validated that this should fix the problem by reducing the magic number to 2 and running minimal tests. I would like to keep the magic number at 30 for now to get proper schema validation.

**Review by isteinbrecher — COMMENTED** [review]
Thanks for looking into this so quickly @sebproell

File: src/global_data/4C_global_data_read.cpp (hunk 1 above)
Comment (isteinbrecher) [reply src/global_data/4C_global_data_read.cpp:88]: That answers my question!

Comment (isteinbrecher) [reply src/global_data/4C_global_data_read.cpp:88]: See previous comment by @sebproell

**Review by isteinbrecher — APPROVED** [review]

File: src/global_data/4C_global_data_read.cpp (hunk 1 above)
Comment (sebproell) [reply src/global_data/4C_global_data_read.cpp:88]: We should definitely work to remove it. I will check with @gilrrei when he is back, if the schema regex features can help us here. On the other hand, the input should really change to something like:

```
FUNCTIONS:
  - ID: 1
    EXPRESSION: x*y
  - ID: 100
    ...
```

But let's not get ahead of ourselves. This would require an automatic input file upgrade mechanism.

**Review by mayrmt — APPROVED** [review]
