### PR TITLE
[ArborX] Update ArborX hash and adjust API

### LINKED ISSUE #291: [ArborX] Newest version breaks backwards compability
## Description: What's going wrong?

Due to changes in the newest version of `ArborX`, our access traits interface breaks.

## Expectations

- [ ] Working interface to `ArborX`.

## Possible Solution

Seems like things break due to changes in template parameters, I guess having a look at those is sufficient.
The relevant changes have been made in: https://github.com/arborx/ArborX/pull/1172
Not sure if there have been additional changes to the API too.

## Steps to Reproduce

1. Build `4C` with the most recent `ArborX` hash.

## Interested Parties

@isteinbrecher @davidrudlstorfer

### PR DESCRIPTION
**Pull request by maxfirmbach**
## Description and Context

This PR updates the `ArborX` hash to the most recent one and adjusts the API to deal with backwards compatibility issues.

## Related Issues and Pull Requests

Closes #291 #290

### CODE REVIEW

**Comment by sebproell** [comment]
@maxfirmbach Try changing [this line](https://github.com/4C-multiphysics/4C/blob/b4e3ee916846df2dee1c78e78e402414cfeb41b3/cmake/configure/configure_ArborX.cmake#L33) to
```
set(FOUR_C_ARBORX_ROOT "${CMAKE_INSTALL_DATADIR}/cmake/ArborX")
```

This was recently changed in ArborX,  https://github.com/arborx/ArborX/commit/03f2007512cde6b353e220a0514610f277f8313c

File: src/core/fem/src/geometric_search/4C_fem_geometric_search_access_traits.hpp [hunk 1]
```diff
@@ -15,45 +15,58 @@
 #ifdef FOUR_C_WITH_ARBORX
 #include <ArborX.hpp>
 
+struct PrimitiveIndexableGetter
+{
+  using memory_space = Kokkos::HostSpace;
+
+  std::vector<FourC::Core::GeometricSearch::BoundingVolume> primitives;
```
Comment (isteinbrecher) [inline src/core/fem/src/geometric_search/4C_fem_geometric_search_access_traits.hpp:22]: I am not 100% sure about this. Can we somehow place a reference/pointer or something to the original primitives vector here instead of copying it? Maybe `std::move`?

Comment (sebproell) [reply src/core/fem/src/geometric_search/4C_fem_geometric_search_access_traits.hpp:22]: @maxfirmbach The field could just be a reference (as suggested by @isteinbrecher) if you only use this struct for the lifetime of the referenced primitives. What you are doing here is essentially what the compiler generates from a lambda expression, except that you give it two operations.

File: src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp [hunk 2]
```diff
@@ -54,13 +54,24 @@ namespace Core::GeometricSearch
...
+      {
+        indexes[id] = primitive.second;
+        id++;
+      }
 
       // Build tree structure containing all primitives.
-      ArborX::BoundingVolumeHierarchy<memory_space> bounding_volume_hierarchy(
-          Kokkos::DefaultExecutionSpace{}, primitives);
+      PrimitiveIndexableGetter indexable{indexes};
+      ArborX::BoundingVolumeHierarchy<memory_space, size_t, indexer_type> bounding_volume_hierarchy{
```
[the remark this answers is not in the document]
Comment (isteinbrecher) [reply src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp:70]: I meant that you are defining an alias `using indexer_type = PrimitiveIndexableGetter` but then here you use the "full" name again.

File: src/core/fem/src/geometric_search/4C_fem_geometric_search_access_traits.hpp (hunk 1 above)
Comment (sebproell) [reply src/core/fem/src/geometric_search/4C_fem_geometric_search_access_traits.hpp:22]: Well. that's correct. Do you have the full trace? Why does this need to be move-assignable? Anyway, you can use a pointer in this case. Or you move the original `primitives` data into the `PrimitiveIndexableGetter` and kept it as a value.

**Comment by isteinbrecher** [comment]
I opened an issue in the ArborX project, to check if we are going in the correct direction with this solution https://github.com/arborx/ArborX/issues/1229.

**Comment by isteinbrecher** [comment]
@maxfirmbach I took the liberty to apply the suggestion from @aprokop (https://github.com/arborx/ArborX/issues/1229#issuecomment-2779104913) and pushed a commit to your branch. What is really nice, that we and we could get rid of the double intersection checks. Locally all geometric search unit tests pass (let's see what the pipeline does), I think we can set this as ready for review.

**Comment by aprokop** [comment]
Just FYI, if you want to be able to build against both previous and new versions of ArborX, you can use `ARBORX_VERSION` macro to hide parts of the code.

**Comment by sebproell** [comment]
@maxfirmbach Just

```
set(FOUR_C_ARBORX_ROOT "${CMAKE_INSTALL_PREFIX}")
```

for now should do it.

**Review by mayrmt — APPROVED** [review]

File: src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp [hunk 3]
```diff
@@ -54,31 +54,26 @@ namespace Core::GeometricSearch
...
-      // primitives with the predicates. With this callback we perform the query in the sense, that
-      // we check each k-DOP of the primitives with each k-DOP of the predicates. This can lead to a
-      // drastic reduction of the found pairs.
-      auto IntersectActualVolumeType =
-          KOKKOS_LAMBDA(const auto predicate, const int primitive_index, const auto& out)->void
-      {
-        const auto& primitive_geometry = primitives[primitive_index].second.bounding_volume_;
+      ArborX::BoundingVolumeHierarchy bounding_volume_hierarchy{
+          execution_space, ArborX::Experimental::attach_indices(
+                               BoundingVolumeVectorPlaceholder<PrimitivesTag>{primitives})};
```
Comment (aprokop) [inline src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp:62]: It seems in your case the predicates are `intersects` based on primitives. This should allow to simplify things further. You can get rid of the tags for `BoundingVolumeVectorPlaceholder` and specialize access traits for it only for primitives. Then, you can use `ArborX::Experimental::make_intersects(BoundingVolumePlaceholder{primitives})` here, which should produce the same result, with ArborX handling specialization for you behind the scenes.

File: src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp [hunk 4]
```diff
@@ -54,31 +54,26 @@ namespace Core::GeometricSearch
...
+          KOKKOS_LAMBDA(const auto predicate, const auto& value, const auto& out)->void
+      {
+        out(value.index);
       };
 
       // Perform the collision check.
-      bounding_volume_hierarchy.query(Kokkos::DefaultExecutionSpace{}, predicates,
-          IntersectActualVolumeType, indices_full, offset_full);
+      bounding_volume_hierarchy.query(execution_space,
+          BoundingVolumeVectorPlaceholder<PredicatesTag>{predicates}, get_indices_callback,
```
Comment (aprokop) [inline src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp:75]: Same as above.

File: src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp (hunk 3 above)
Comment (isteinbrecher) [reply src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp:62]: Thanks a lot for the suggestion @aprokop, I didn't know such a thing like `make_intersects` exists. I tried it but got the following error:
```
src/spatial/detail/ArborX_PredicateHelpers.hpp:81:52: error: could not convert 'primitives' from 'const FourC::Core::GeometricSearch::BoundingVolumeVectorPlaceholder' to 'ArborX::Experimental::PrimitivesIntersect<FourC::Core::GeometricSearch::BoundingVolumeVectorPlaceholder>::Primitives' {aka 'ArborX::Details::AccessValuesI<FourC::Core::GeometricSearch::BoundingVolumeVectorPlaceholder>'}
   81 |   return PrimitivesIntersect<Primitives>{primitives};
      |                                                    ^
      |                                                    |
      |                                                    const FourC::Core::GeometricSearch::BoundingVolumeVectorPlaceholder
```
It is possible, that the primitives type can't automatically be detected from the user data type and I have to specify it explicitly?

Comment (aprokop) [reply src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp:62]: @isteinbrecher I'm not sure what's happening. Could you please post a patch that you tried? `make_intersects` is templated, so they types are automatically determined without any need for deduction guides.

Comment (isteinbrecher) [reply src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp:62]: Sure, I uploaded the non working version to the following branch (the "breaking" changes are in the last commit) https://github.com/isteinbrecher/4C/tree/improve-use-of-arborx

Comment (aprokop) [reply src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp:62]: You are right. This is a bug in ArborX, which allows `make_intersects` work when using `Kokkos::View<Geometry*,...>` but fail when used with `AccessTraits`. I'll fix it. This is why it's still in `Experimental` :(

Comment (isteinbrecher) [reply src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp:62]: Thanks for the explanation. If we can help by providing some sample code or a test let us know, we would be happy to help.

File: src/core/fem/src/geometric_search/4C_fem_geometric_search_access_traits.hpp [hunk 5]
```diff
@@ -15,48 +15,53 @@
...
-        std::size_t i)
+    static KOKKOS_FUNCTION auto get(
+        const BoundingVolumeVectorPlaceholder<PredicatesTag>& placeholder, size_type i)
     {
-      auto const& vector_entry = vector[i];
-      return intersects(vector_entry.second.bounding_volume_);
+      return intersects(placeholder.bounding_volumes_[i].second.bounding_volume_);
     }
   };
 }  // namespace ArborX
```
[the remark this answers is not in the document]
Comment (isteinbrecher) [reply src/core/fem/src/geometric_search/4C_fem_geometric_search_access_traits.hpp:67]: I will fix this, then I think we can proceed with this PR.

File: src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp (hunk 3 above)
Comment (mayrmt) [reply src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp:62]: @isteinbrecher What does this mean for this PR? I'd suggest to proceed and get the fix from ArborX at some point in the future.

Comment (isteinbrecher) [reply src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp:62]: I just pushed a final small fix, we can proceed with merging this. I have some other ideas to clean up our ArborX interface, but I will do that in a separate PR.

**Review by mayrmt — APPROVED** [review]

**Review by sebproell — APPROVED** [review]

**Comment by aprokop** [comment]
@isteinbrecher The fix for ArborX' `make_intersects` been merged to master. Now your patch should work.

**Comment by isteinbrecher** [comment]
@aprokop thanks for the info, I will have a look at this next week.
